// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/forzeyy/avito-internship-spring-service/internal/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PVZService is an autogenerated mock type for the PVZService type
type PVZService struct {
	mock.Mock
}

type PVZService_Expecter struct {
	mock *mock.Mock
}

func (_m *PVZService) EXPECT() *PVZService_Expecter {
	return &PVZService_Expecter{mock: &_m.Mock}
}

// CreatePVZ provides a mock function with given fields: ctx, city
func (_m *PVZService) CreatePVZ(ctx context.Context, city string) (*models.PVZ, error) {
	ret := _m.Called(ctx, city)

	if len(ret) == 0 {
		panic("no return value specified for CreatePVZ")
	}

	var r0 *models.PVZ
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PVZ, error)); ok {
		return rf(ctx, city)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PVZ); ok {
		r0 = rf(ctx, city)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PVZ)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, city)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PVZService_CreatePVZ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePVZ'
type PVZService_CreatePVZ_Call struct {
	*mock.Call
}

// CreatePVZ is a helper method to define mock.On call
//   - ctx context.Context
//   - city string
func (_e *PVZService_Expecter) CreatePVZ(ctx interface{}, city interface{}) *PVZService_CreatePVZ_Call {
	return &PVZService_CreatePVZ_Call{Call: _e.mock.On("CreatePVZ", ctx, city)}
}

func (_c *PVZService_CreatePVZ_Call) Run(run func(ctx context.Context, city string)) *PVZService_CreatePVZ_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PVZService_CreatePVZ_Call) Return(_a0 *models.PVZ, _a1 error) *PVZService_CreatePVZ_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PVZService_CreatePVZ_Call) RunAndReturn(run func(context.Context, string) (*models.PVZ, error)) *PVZService_CreatePVZ_Call {
	_c.Call.Return(run)
	return _c
}

// GetPVZs provides a mock function with given fields: ctx, startDate, endDate, page, limit
func (_m *PVZService) GetPVZs(ctx context.Context, startDate *time.Time, endDate *time.Time, page int, limit int) ([]models.PVZ, error) {
	ret := _m.Called(ctx, startDate, endDate, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPVZs")
	}

	var r0 []models.PVZ
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, int) ([]models.PVZ, error)); ok {
		return rf(ctx, startDate, endDate, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, int) []models.PVZ); ok {
		r0 = rf(ctx, startDate, endDate, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PVZ)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *time.Time, *time.Time, int, int) error); ok {
		r1 = rf(ctx, startDate, endDate, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PVZService_GetPVZs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPVZs'
type PVZService_GetPVZs_Call struct {
	*mock.Call
}

// GetPVZs is a helper method to define mock.On call
//   - ctx context.Context
//   - startDate *time.Time
//   - endDate *time.Time
//   - page int
//   - limit int
func (_e *PVZService_Expecter) GetPVZs(ctx interface{}, startDate interface{}, endDate interface{}, page interface{}, limit interface{}) *PVZService_GetPVZs_Call {
	return &PVZService_GetPVZs_Call{Call: _e.mock.On("GetPVZs", ctx, startDate, endDate, page, limit)}
}

func (_c *PVZService_GetPVZs_Call) Run(run func(ctx context.Context, startDate *time.Time, endDate *time.Time, page int, limit int)) *PVZService_GetPVZs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*time.Time), args[2].(*time.Time), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *PVZService_GetPVZs_Call) Return(_a0 []models.PVZ, _a1 error) *PVZService_GetPVZs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PVZService_GetPVZs_Call) RunAndReturn(run func(context.Context, *time.Time, *time.Time, int, int) ([]models.PVZ, error)) *PVZService_GetPVZs_Call {
	_c.Call.Return(run)
	return _c
}

// NewPVZService creates a new instance of PVZService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPVZService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PVZService {
	mock := &PVZService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
