// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/forzeyy/avito-internship-spring-service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// ReceptionService is an autogenerated mock type for the ReceptionService type
type ReceptionService struct {
	mock.Mock
}

type ReceptionService_Expecter struct {
	mock *mock.Mock
}

func (_m *ReceptionService) EXPECT() *ReceptionService_Expecter {
	return &ReceptionService_Expecter{mock: &_m.Mock}
}

// CloseLastReception provides a mock function with given fields: ctx, pvzID
func (_m *ReceptionService) CloseLastReception(ctx context.Context, pvzID string) (*models.Reception, error) {
	ret := _m.Called(ctx, pvzID)

	if len(ret) == 0 {
		panic("no return value specified for CloseLastReception")
	}

	var r0 *models.Reception
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Reception, error)); ok {
		return rf(ctx, pvzID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Reception); ok {
		r0 = rf(ctx, pvzID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Reception)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pvzID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReceptionService_CloseLastReception_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseLastReception'
type ReceptionService_CloseLastReception_Call struct {
	*mock.Call
}

// CloseLastReception is a helper method to define mock.On call
//   - ctx context.Context
//   - pvzID string
func (_e *ReceptionService_Expecter) CloseLastReception(ctx interface{}, pvzID interface{}) *ReceptionService_CloseLastReception_Call {
	return &ReceptionService_CloseLastReception_Call{Call: _e.mock.On("CloseLastReception", ctx, pvzID)}
}

func (_c *ReceptionService_CloseLastReception_Call) Run(run func(ctx context.Context, pvzID string)) *ReceptionService_CloseLastReception_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ReceptionService_CloseLastReception_Call) Return(_a0 *models.Reception, _a1 error) *ReceptionService_CloseLastReception_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReceptionService_CloseLastReception_Call) RunAndReturn(run func(context.Context, string) (*models.Reception, error)) *ReceptionService_CloseLastReception_Call {
	_c.Call.Return(run)
	return _c
}

// CreateReception provides a mock function with given fields: ctx, pvzID
func (_m *ReceptionService) CreateReception(ctx context.Context, pvzID string) (*models.Reception, error) {
	ret := _m.Called(ctx, pvzID)

	if len(ret) == 0 {
		panic("no return value specified for CreateReception")
	}

	var r0 *models.Reception
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Reception, error)); ok {
		return rf(ctx, pvzID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Reception); ok {
		r0 = rf(ctx, pvzID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Reception)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pvzID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReceptionService_CreateReception_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReception'
type ReceptionService_CreateReception_Call struct {
	*mock.Call
}

// CreateReception is a helper method to define mock.On call
//   - ctx context.Context
//   - pvzID string
func (_e *ReceptionService_Expecter) CreateReception(ctx interface{}, pvzID interface{}) *ReceptionService_CreateReception_Call {
	return &ReceptionService_CreateReception_Call{Call: _e.mock.On("CreateReception", ctx, pvzID)}
}

func (_c *ReceptionService_CreateReception_Call) Run(run func(ctx context.Context, pvzID string)) *ReceptionService_CreateReception_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ReceptionService_CreateReception_Call) Return(_a0 *models.Reception, _a1 error) *ReceptionService_CreateReception_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReceptionService_CreateReception_Call) RunAndReturn(run func(context.Context, string) (*models.Reception, error)) *ReceptionService_CreateReception_Call {
	_c.Call.Return(run)
	return _c
}

// NewReceptionService creates a new instance of ReceptionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReceptionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReceptionService {
	mock := &ReceptionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
